### ISSUE TITLE
Features section seems non-uniform

### ISSUE THREAD

**Issue by Shivansh175** [SaptarshiSarkar12/Drifty#303] opened 2023-10-05 14:19 UTC
### Description

The features section in your website seems quite non uniform as it does not follow the principles of symmetry highly essential for a visually appealing UI design. UI design can be enhanced if all the boxes (under features section) resembles in shape and size (height here).

Here is the SS of what i want to convey...
![Screenshot 2023-10-05 194334](https://github.com/SaptarshiSarkar12/Drifty/assets/112273961/74e4a586-a201-41f5-b362-face6113c3c2)
this section would have been looking better if all the cards within it are of same shape n size.

**Comment by SaptarshiSarkar12** [comment] 2023-10-05 15:21
Thank you for opening the issue @Shivansh175!
Sorry, currently, the features cards have the correct space they require, and I do not think keeping a symmetry would make it look good.
Also, **this issue is a duplicate of #299**.
So, may I close this issue? Do have any other idea in your mind?

**Comment by Shivansh175** [comment] 2023-10-05 16:06
ohh didn't notice #299 if you think so u can close the issue then :)

**Comment by SaptarshiSarkar12** [comment] 2023-10-05 16:12
It is okay. 
I am closing this issue.
Thank you!

**Closed by SaptarshiSarkar12** 2023-10-05 16:12 UTC
Labels: bug 🐛, duplicate, wontfix ❌, Website 🌐
